DROP SEQUENCE SCORESEQ;
DROP TABLE SCREBOARD;

CREATE SEQUENCE SCORESEQ;

CREATE TABLE SCREBOARD(
	S_NO NUMBER PRIMARY KEY,
	S_NAME VARCHAR2(20) NOT NULL,
	S_KOR NUMBER NOT NULL,
	S_ENG NUMBER NOT NULL,
	S_MATH NUMBER NOT NULL,
	S_SUM NUMBER,
	S_AVG NUMBER,
	S_GRADE VARCHAR2(2) CHECK(S_GRADE IN ('A', 'B', 'C', 'D', 'F'))
);

INSERT INTO SCREBOARD(S_NO, S_NAME, S_KOR, S_ENG, S_MATH)
VALUES(SCORESEQ.NEXTCAL, '천재', 100, 100, 100);

SELECT S_NO, S_NAME, S_KOR, S_ENG, S_MATH, S_SUM, S_AVG, S_GRADE
FROM SCREBOARD
ORDER BY S_NO DESC;